# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <cast_df_to_sf>
  # <infra_guess_crs>
  "infra_x_column_names",
  # <cast_df_to_sf>
  # <infra_guess_crs>
  "infra_y_column_names",
  NULL
))
